### ISSUE TITLE
Incompatible with NVSE 5.14

### ISSUE THREAD

**Issue by AVeryUncreativeUsername** [Demorome/Showoff-NVSE#17]
Can u pls maek this combatibal wit old NVSE so I can use sum sertain.....mods that dont work wif new NVSE? thx

**Comment by Demorome** [comment]
old NVSE is not very showoff tbh, shouldn't be supported
![image](https://user-images.githubusercontent.com/69116996/130538971-413a90d1-5be1-458e-adea-3d8258bb35d3.png)
