### ISSUE TITLE
Soft crash with TTW

### ISSUE THREAD

**Issue by PhlexPythonNovice** [Demorome/Showoff-NVSE#29]
Error message on boot: Showoff xNVSE: Error detected while trying to hook to the game: please report what you see in the log file.

Log: Cannot write call at hook address 0x785087; another hook made it no longer a function call.

FNV/FO3 version: GOG
Raw install according to Wasteland Survival Guide, no other mods present.
Running MO2 and game as administrator.

Could you please check? Thank you!

**Comment by zalifsif38** [comment]
Same problem here

**Comment by Demorome** [comment]
Should be fixed now.
