### ISSUE TITLE
ShowOff xNVSE seems to break plugins that change how we interact with knocked out NPCs

### ISSUE THREAD

**Issue by Superfly-Johnson** [Demorome/Showoff-NVSE#30]
I have been painstakingly going through my entire load order to figure out what caused [Fatigue Overhaul](https://www.nexusmods.com/newvegas/mods/78111)'s knockout menu to not work. After disabling showoff xNVSE using Mod Organizer the mod finally worked.

Any idea why showoff xNVSE is conflicting with this mod in particular?

**Comment by Demorome** [comment]
I believe it is likely due to a bug in 1.72 that prevented ShowOff from loading under certain conditions, probably preventing other plugins from loading as well if they didn't load yet.
Try with 1.73.

**Comment by Superfly-Johnson** [comment]
> I believe it is likely due to a bug in 1.72 that prevented ShowOff from loading under certain conditions, probably preventing other plugins from loading as well if they didn't load yet. Try with 1.73.

I shall, thanks for your response.

SWIFT EDIT: I'm already using 1.73, so the issue is still present

**Comment by Demorome** [comment]
Fixed in 1.74, thanks for the swift reply!

**Comment by Superfly-Johnson** [comment]
👍 Ty for your work!
