### ISSUE TITLE
CTD with the mod enabled.

### ISSUE THREAD

**Issue by DarthGamerV** [Demorome/Showoff-NVSE#31]
Tested with all available versions on Nexus. Game works fine without it, but when re-enabling the .dll/mod it crashes to desktop.

Here is the crash logs that point to it. Tried to disable multiple other possible cullprits, but the game only crashes with ShowOff enabled =/

[CrashLogger.2024-01-25-04-17-32.log](https://github.com/Demorome/ShowOff-NVSE/files/14046916/CrashLogger.2024-01-25-04-17-32.log)
[CrashLogger.2024-01-25-04-13-20.log](https://github.com/Demorome/ShowOff-NVSE/files/14046917/CrashLogger.2024-01-25-04-13-20.log)
[Uploading CrashLogger.2024-01-25-04-28-36.log…](
[CrashLogger.2024-01-25-04-24-43.log](https://github.com/Demorome/ShowOff-NVSE/files/14046915/CrashLogger.2024-01-25-04-24-43.log)

[CrashLogger.2024-01-25-04-25-50.log](https://github.com/Demorome/ShowOff-NVSE/files/14046914/CrashLogger.2024-01-25-04-25-50.log)
)

[CrashLogger.2024-01-25-04-35-12.log](https://github.com/Demorome/ShowOff-NVSE/files/14046911/CrashLogger.2024-01-25-04-35-12.log)
[CrashLogger.2024-01-25-04-31-13.log](https://github.com/Demorome/ShowOff-NVSE/files/14046912/CrashLogger.2024-01-25-04-31-13.log)

**Comment by Demorome** [comment]
It was a crash related to a missing nullcheck in GetEquippedWeaponRef, which is now fixed.
